import type { Module, Question } from './types';

export const MODULES: Module[] = Array.from({ length: 27 }, (_, i) => ({
  id: `M${i + 1}`,
  title: `Module ${i + 1} — Traffic Rules & Safety`,
  progress: Math.floor(Math.random() * 100),
}));

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'q1',
    moduleId: 'M1',
    text: 'C avtomobilinin sürücüsü bu şəraitdə hansı nəqliyyat vasitələrinə yol verməlidir?',
    imageUrl: 'https://images.pexels.com/photos/163064/play-stone-network-networked-interactive-163064.jpeg?auto=compress&cs=tinysrgb&w=800',
    options: [
      { id: 'o1', text: 'Yalnız 1 №-li tramvaya.' },
      { id: 'o2', text: 'Yalnız 2 №-li tramvaya.' },
      { id: 'o3', text: 'Yalnız 2 №-li tramvaya və B avtomobilinə.' },
      { id: 'o4', text: 'Tramvaylara, B və D avtomobillərinə.' },
    ],
    correctOptionId: 'o2',
    explanation: 'Yan göstəricilərə əsasən C avtomobili sol tərəfdən gələn 2 №-li tramvaya və sağdan gələn B avtomobilinə yol verməlidir.',
  },
  {
    id: 'q2',
    moduleId: 'M1',
    text: 'Şəkildə neçə yolayrıcı göstərilmişdir?',
    options: [
      { id: 'o1', text: '1' },
      { id: 'o2', text: '2' },
      { id: 'o3', text: '3' },
      { id: 'o4', text: '4' },
    ],
    correctOptionId: 'o2',
    explanation: 'Sxemdə iki ayrı yolayrıcı aydın görünür.',
  },
  {
    id: 'q3',
    moduleId: 'M1',
    text: 'Bu şəraitdə hansı avtomobil tramvaya nisbətən üstünlüyə malikdir?',
    options: [
      { id: 'o1', text: 'A avtomobili' },
      { id: 'o2', text: 'B avtomobili' },
      { id: 'o3', text: 'C avtomobili' },
      { id: 'o4', text: 'Heç biri' },
    ],
    correctOptionId: 'o2',
    explanation: 'Dairəvi hərəkətdə B avtomobilinin hərəkət üstünlüyü verilmişdir.',
  },
  {
    id: 'q4',
    moduleId: 'M1',
    text: 'Bu şəraitdə hansı avtomobilin sürücüsü digər avtomobillərə yol vermədən hərəkəti davam etdirə bilər?',
    options: [
      { id: 'o1', text: 'Solda yerləşən avtomobil' },
      { id: 'o2', text: 'Sağda yerləşən avtomobil' },
      { id: 'o3', text: 'Düz hərəkət edən avtomobil' },
      { id: 'o4', text: 'Heç biri' },
    ],
    correctOptionId: 'o2',
    explanation: 'Düz istiqamətə hərəkət edən nəqliyyat vasitəsi yolayrıcıda üstünlüyə malikdir.',
  },
  {
    id: 'q5',
    moduleId: 'M1',
    text: 'Yolayrıcıdan sonra siz hansı hərəkətə girə bilərsiniz?',
    options: [
      { id: 'o1', text: 'Yalnız sola dönə bilərsiniz' },
      { id: 'o2', text: 'Yalnız sağa dönə bilərsiniz' },
      { id: 'o3', text: 'Düz gedə və sağa dönə bilərsiniz' },
      { id: 'o4', text: 'Düz gedə və sola dönə bilərsiniz' },
    ],
    correctOptionId: 'o2',
    explanation: 'Yol nişanları düz və sağa hərəkətə icazə verir.',
  },
  {
    id: 'q6',
    moduleId: 'M1',
    text: 'Qoşqu aparan minik avtomobilində hansı maksimal sürətlə hərəkəti davam etdirə bilərsiniz?',
    options: [
      { id: 'o1', text: '60 km/saat' },
      { id: 'o2', text: '70 km/saat' },
      { id: 'o3', text: '80 km/saat' },
      { id: 'o4', text: '90 km/saat' },
    ],
    correctOptionId: 'o3',
    explanation: 'Qoşqu ilə hərəkətdə ümumi limit adətən 80 km/saatdır.',
  },
  {
    id: 'q7',
    moduleId: 'M1',
    text: 'Bu şəraitdə sizə dəmir yol keçidinə daxil olmağa icazə verilir?',
    options: [
      { id: 'o1', text: 'Bəli, maneə yoxdursa' },
      { id: 'o2', text: 'Xeyr, siqnal verilir' },
      { id: 'o3', text: 'Yalnız tıxac olduqda' },
      { id: 'o4', text: 'Məşq zamanı mümkündür' },
    ],
    correctOptionId: 'o2',
    explanation: 'Qırmızı işıq və ya maneə göstəricisi olduqda keçidə daxil olmaq qadağandır.',
  },
  {
    id: 'q8',
    moduleId: 'M1',
    text: 'İşçi tormoz sistemi nasaz olan avtomobili necə yedəyə almaq olar?',
    options: [
      { id: 'o1', text: 'Yalnız bərk yedəklə' },
      { id: 'o2', text: 'Yalnız elastik yedəklə' },
      { id: 'o3', text: 'Bərk və ya elastik yedəklə, şərtlə ki, çəkən avtomobilin kütləsi daha çox olsun' },
      { id: 'o4', text: 'Ümumiyyətlə qadağandır' },
    ],
    correctOptionId: 'o2',
    explanation: 'Çəkmə qaydalarına əsasən faktiki kütlə tələbləri ödənilməlidir.',
  },
  {
    id: 'q9',
    moduleId: 'M1',
    text: 'Travmatik şoka düşmüş zərərçəkənə ilk yardımın əsas məqsədi nədir?',
    options: [
      { id: 'o1', text: 'Ağrını artırmaq' },
      { id: 'o2', text: 'Sakitlik və hərəkətsizliyi təmin etmək, bədəni isti saxlamaq' },
      { id: 'o3', text: 'Su içirmək' },
      { id: 'o4', text: 'Dərhal hərəkət etdirmək' },
    ],
    correctOptionId: 'o2',
    explanation: 'Şok zamanı hərəkətsizlik, istilik və təcili tibbi yardımın çağırılması vacibdir.',
  },
  {
    id: 'q10',
    moduleId: 'M1',
    text: 'Siz ağ rəngli avtomobili idarə edirsiniz. Bu şəraitdə kimlərə hərəkəti davam etdirməyə icazə verilir?',
    options: [
      { id: 'o1', text: 'Yalnız sizə' },
      { id: 'o2', text: 'Sizə və sağdakı avtomobilə' },
      { id: 'o3', text: 'Yalnız sağdakı avtomobilə' },
      { id: 'o4', text: 'Heç kimə' },
    ],
    correctOptionId: 'o2',
    explanation: 'İşarələrin tələbinə görə eyni istiqamətli iki nəqliyyat vasitəsi hərəkəti davam etdirə bilər.',
  },
];
