import type { Module, Question } from './types';

const MODULE_TITLES: string[] = [
  'M1. Ümumi müddəalar',
  'M2. Yol hərəkəti iştirakçılarının vəzifələri, NV-nin idarəetmə hüququ, sürücülük vəsiqəsi',
  'M3. Yol nişanları',
  'M4. Yolun nişanlanma xətləri',
  'M5. Nizamlayıcının və svetoforların siqnalları',
  'M6. Xüsusi siqnalların tətbiqi',
  'M7. Qəza dayanma siqnalının və qəza dayanma nişanının tətbiqi',
  'M8. Hərəkətə başlama və manevretmə',
  'M9. NV-nin yolun hərəkət hissəsində yerləşdiyilməsi',
  'M10. Hərəkət sürəti',
  'M11. Ötmə və qarşılıqlı keçmə',
  'M12. Dayanma, durma və parklanma',
  'M13. Yolayrıcıların keçilməsi',
  'M14. Piyada keçidləri və ümumi istifadədə olan NV-nin dayanması',
  'M15. Avtomagistrallarda hərəkət',
  'M16. Dəmiryol keçidlərində hərəkət',
  'M17. NV-nin üstün hərəkət rejimi ilə hərəkəti və bununla əlaqədar digər sürücülərin vəzifələri',
  'M18. Yaşayış zonalarında hərəkət. Sürmə təlimi',
  'M19. NV-də səs siqnalları və xarici işıq cihazlarının istifadə edilməsi',
  'M20. Nasaz NV və onların yedəyə alınması',
  'M21. Adamların və yüklərin daşınması',
  'M22. NV-nin nasazlıqları və istismarı qadağan edən səbəblər',
  'M23. Yol hərəkəti təhlükəsizliyinin əsasları',
  'M24. İlk tibbi yardımın göstərilməsi',
  'M25. Velosiped, kiçik elektik nəqliyyat vasitələri, moped və at arabalarının sürülməsinə dair tələblər',
  'M26. Sürücülərin cavabdehliyi',
  'M27. Avtomobilin quruluşu',
];

export const MODULES: Module[] = MODULE_TITLES.map((title, idx) => ({
  id: `M${idx + 1}`,
  title,
  progress: Math.floor(Math.random() * 100),
}));

export type ExamTopic = {
  id: number;
  title: string;
  subtopics?: string[];
};

export const EXAM_TOPICS: ExamTopic[] = [
  { id: 1, title: 'M1. Ümumi müddəalar' },
  {
    id: 2,
    title: 'M2. Yol hərəkəti iştirakçılarının vəzifələri, NV-nin idarəetmə hüququ, sürücülük vəsiqəsi',
    subtopics: [
      '2.1. NV-nin idarəetmə hüququ. Sürücülük vəsiqəsi.',
      '2.2. Yol hərəkəti iştirakçılarının vəzifələri.',
    ],
  },
  {
    id: 3,
    title: 'M3. Yol nişanları',
    subtopics: [
      '3.1. Yol nişanlarının tətbiqi. Xəbərdarlıq nişanları.',
      '3.2. Üstünlük nişanları.',
      '3.3. Qadağan nişanları.',
      '3.4. Məcburi hərəkət istiqaməti nişanları.',
      '3.5. Məlumatverici-göstərici nişanlar.',
      '3.6. Servis nişanları.',
      '3.7. Əlavə məlumat nişanları (lövhəcikləri).',
      '3.8. Nəqliyyat vasitələrinin tanınma nişanları.',
    ],
  },
  { id: 4, title: 'M4. Yolun nişanlanma xətləri' },
  { id: 5, title: 'M5. Nizamlayıcının və svetoforların siqnalları' },
  { id: 6, title: 'M6. Xüsusi siqnalların tətbiqi' },
  { id: 7, title: 'M7. Qəza dayanma siqnalının və qəza dayanma nişanının tətbiqi' },
  { id: 8, title: 'M8. Hərəkətə başlama və manevretmə' },
  { id: 9, title: 'M9. NV-nin yolun hərəkət hissəsində yerləşdiyilməsi' },
  { id: 10, title: 'M10. Hərəkət sürəti' },
  { id: 11, title: 'M11. Ötmə və qarşılıqlı keçmə' },
  { id: 12, title: 'M12. Dayanma, durma və parklanma' },
  { id: 13, title: 'M13. Yolayrıcıların keçilməsi' },
  { id: 14, title: 'M14. Piyada keçidləri və ümumi istifadədə olan NV-nin dayanması' },
  { id: 15, title: 'M15. Avtomagistrallarda hərəkət' },
  { id: 16, title: 'M16. Dəmiryol keçidlərində hərəkət' },
  { id: 17, title: 'M17. NV-nin üstün hərəkət rejimi ilə hərəkəti və bununla əlaqədar digər sürücülərin vəzifələri' },
  { id: 18, title: 'M18. Yaşayış zonalarında hərəkət. Sürmə təlimi' },
  { id: 19, title: 'M19. NV-də səs siqnalları və xarici işıq cihazlarının istifadə edilməsi' },
  { id: 20, title: 'M20. Nasaz NV və onların yedəyə alınması' },
  { id: 21, title: 'M21. Adamların və yüklərin daşınması' },
  { id: 22, title: 'M22. NV-nin nasazlıqları və istismarı qadağan edən səbəblər' },
  { id: 23, title: 'M23. Yol hərəkəti təhlükəsizliyinin əsasları' },
  { id: 24, title: 'M24. İlk tibbi yardımın göstərilməsi' },
  { id: 25, title: 'M25. Velosiped, kiçik elektik nəqliyyat vasitələri, moped və at arabalarının sürülməsinə dair tələblər' },
  { id: 26, title: 'M26. Sürücülərin cavabdehliyi' },
  {
    id: 27,
    title: 'M27. Avtomobilin quruluşu',
    subtopics: [
      '27.1 Avtomobilin ümumi quruluşu',
      '27.2 Benzin DYM',
      '27.3 Dizel DYM',
      '27.4 Çarxqolu-sürgüqolu mexanizmi',
      '27.5 Qaz paylama mexanizmi',
    ],
  },
];

export const SAMPLE_QUESTIONS: Question[] = [
  {
    id: 'q1',
    moduleId: 'M1',
    text: 'C avtomobilinin sürücüsü bu şəraitdə hansı nəqliyyat vasitələrinə yol verməlidir?',
    imageUrl: 'https://images.pexels.com/photos/163064/play-stone-network-networked-interactive-163064.jpeg?auto=compress&cs=tinysrgb&w=800',
    options: [
      { id: 'o1', text: 'Yalnız 1 №-li tramvaya.' },
      { id: 'o2', text: 'Yalnız 2 №-li tramvaya.' },
      { id: 'o3', text: 'Yalnız 2 №-li tramvaya və B avtomobilinə.' },
      { id: 'o4', text: 'Tramvaylara, B və D avtomobillərinə.' },
    ],
    correctOptionId: 'o2',
    explanation: 'Yan göstəricilərə əsasən C avtomobili sol tərəfdən gələn 2 №-li tramvaya və sağdan gələn B avtomobilinə yol verməlidir.',
  },
  {
    id: 'q2',
    moduleId: 'M1',
    text: 'Şəkildə neçə yolayrıcı göstərilmişdir?',
    options: [
      { id: 'o1', text: '1' },
      { id: 'o2', text: '2' },
      { id: 'o3', text: '3' },
      { id: 'o4', text: '4' },
    ],
    correctOptionId: 'o2',
    explanation: 'Sxemdə iki ayrı yolayrıcı aydın görünür.',
  },
  {
    id: 'q3',
    moduleId: 'M1',
    text: 'Bu şəraitdə hansı avtomobil tramvaya nisbətən üstünlüyə malikdir?',
    options: [
      { id: 'o1', text: 'A avtomobili' },
      { id: 'o2', text: 'B avtomobili' },
      { id: 'o3', text: 'C avtomobili' },
      { id: 'o4', text: 'Heç biri' },
    ],
    correctOptionId: 'o2',
    explanation: 'Dairəvi hərəkətdə B avtomobilinin hərəkət üstünlüyü verilmişdir.',
  },
  {
    id: 'q4',
    moduleId: 'M1',
    text: 'Bu şəraitdə hansı avtomobilin sürücüsü digər avtomobillərə yol vermədən hərəkəti davam etdirə bilər?',
    options: [
      { id: 'o1', text: 'Solda yerləşən avtomobil' },
      { id: 'o2', text: 'Sağda yerləşən avtomobil' },
      { id: 'o3', text: 'Düz hərəkət edən avtomobil' },
      { id: 'o4', text: 'Heç biri' },
    ],
    correctOptionId: 'o2',
    explanation: 'Düz istiqamətə hərəkət edən nəqliyyat vasitəsi yolayrıcıda üstünlüyə malikdir.',
  },
  {
    id: 'q5',
    moduleId: 'M1',
    text: 'Yolayrıcıdan sonra siz hansı hərəkətə girə bilərsiniz?',
    options: [
      { id: 'o1', text: 'Yalnız sola dönə bilərsiniz' },
      { id: 'o2', text: 'Yalnız sağa dönə bilərsiniz' },
      { id: 'o3', text: 'Düz gedə və sağa dönə bilərsiniz' },
      { id: 'o4', text: 'Düz gedə və sola dönə bilərsiniz' },
    ],
    correctOptionId: 'o2',
    explanation: 'Yol nişanları düz və sağa hərəkətə icazə verir.',
  },
  {
    id: 'q6',
    moduleId: 'M1',
    text: 'Qoşqu aparan minik avtomobilində hansı maksimal sürətlə hərəkəti davam etdirə bilərsiniz?',
    options: [
      { id: 'o1', text: '60 km/saat' },
      { id: 'o2', text: '70 km/saat' },
      { id: 'o3', text: '80 km/saat' },
      { id: 'o4', text: '90 km/saat' },
    ],
    correctOptionId: 'o3',
    explanation: 'Qoşqu ilə hərəkətdə ümumi limit adətən 80 km/saatdır.',
  },
  {
    id: 'q7',
    moduleId: 'M1',
    text: 'Bu şəraitdə sizə dəmir yol keçidinə daxil olmağa icazə verilir?',
    options: [
      { id: 'o1', text: 'Bəli, maneə yoxdursa' },
      { id: 'o2', text: 'Xeyr, siqnal verilir' },
      { id: 'o3', text: 'Yalnız tıxac olduqda' },
      { id: 'o4', text: 'Məşq zamanı mümkündür' },
    ],
    correctOptionId: 'o2',
    explanation: 'Qırmızı işıq və ya maneə göstəricisi olduqda keçidə daxil olmaq qadağandır.',
  },
  {
    id: 'q8',
    moduleId: 'M1',
    text: 'İşçi tormoz sistemi nasaz olan avtomobili necə yedəyə almaq olar?',
    options: [
      { id: 'o1', text: 'Yalnız bərk yedəklə' },
      { id: 'o2', text: 'Yalnız elastik yedəklə' },
      { id: 'o3', text: 'Bərk və ya elastik yedəklə, şərtlə ki, çəkən avtomobilin kütləsi daha çox olsun' },
      { id: 'o4', text: 'Ümumiyyətlə qadağandır' },
    ],
    correctOptionId: 'o2',
    explanation: 'Çəkmə qaydalarına əsasən faktiki kütlə tələbləri ödənilməlidir.',
  },
  {
    id: 'q9',
    moduleId: 'M1',
    text: 'Travmatik şoka düşmüş zərərçəkənə ilk yardımın əsas məqsədi nədir?',
    options: [
      { id: 'o1', text: 'Ağrını artırmaq' },
      { id: 'o2', text: 'Sakitlik və hərəkətsizliyi təmin etmək, bədəni isti saxlamaq' },
      { id: 'o3', text: 'Su içirmək' },
      { id: 'o4', text: 'Dərhal hərəkət etdirmək' },
    ],
    correctOptionId: 'o2',
    explanation: 'Şok zamanı hərəkətsizlik, istilik və təcili tibbi yardımın çağırılması vacibdir.',
  },
  {
    id: 'q10',
    moduleId: 'M1',
    text: 'Siz ağ rəngli avtomobili idarə edirsiniz. Bu şəraitdə kimlərə hərəkəti davam etdirməyə icazə verilir?',
    options: [
      { id: 'o1', text: 'Yalnız sizə' },
      { id: 'o2', text: 'Sizə və sağdakı avtomobilə' },
      { id: 'o3', text: 'Yalnız sağdakı avtomobilə' },
      { id: 'o4', text: 'Heç kimə' },
    ],
    correctOptionId: 'o2',
    explanation: 'İşarələrin tələbinə görə eyni istiqamətli iki nəqliyyat vasitəsi hərəkəti davam etdirə bilər.',
  },
];
